#!/bin/sh
docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
docker tag $ORG_GRADLE_PROJECT_group/$ORG_GRADLE_PROJECT_applicationName:latest $DOCKER_REGISTRY/$IMAGE_GROUP/$IMAGE_NAME:$GO_PIPELINE_LABEL
docker push $DOCKER_REGISTRY/$IMAGE_GROUP/$IMAGE_NAME:$GO_PIPELINE_LABEL
docker rmi -f $ORG_GRADLE_PROJECT_group/$ORG_GRADLE_PROJECT_applicationName:latest
docker rmi -f $DOCKER_REGISTRY/$IMAGE_GROUP/$IMAGE_NAME:$GO_PIPELINE_LABEL
